class echoes_alert::params {
  $branch              = 'master'
  $version             = 'latest'
  $install_dir         = '/opt/echoes-alert'
  $log_dir             = '/var/log/echoes-alert'
  $postgresql_ipv4acls = []
  $database_host       = '127.0.0.1'
  $database_name       = 'echoes'
  $database_user       = 'echoes'
  $database_password   = 'echoes'
  $serveralias         = []
  $http_port           = 80
  $https_port          = 443
  $api_host            = 'alert-api.echoes-tech.com'
  $gui_host            = 'alert.echoes-tech.com'
  $simulator_host      = 'alert-simulator.echoes-tech.com'
  $smtp_host           = 'localhost'
  $addons              = {
    'common'     => {},
    'file'       => {},
    'filesystem' => {},
    'hash'       => {},
    'log'        => {},
    'odbc'       => {},
    'process'    => {},
    'snmp'       => {},
    'xml'        => {}
  }
}
